package com.tmi.backend.global.error;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

  /* 1. COMMON – 공통 */
  COMMON_INVALID_FORMAT(HttpStatus.BAD_REQUEST, "COMMON-001"),
  COMMON_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON-002"),
  COMMON_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "COMMON-003"),

  /* 2. AUTH – 인증/인가 */
  AUTH_INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH-001"),
  AUTH_ACCESS_DENIED(HttpStatus.FORBIDDEN, "AUTH-002"),
  AUTH_DUPLICATE_ACCOUNT(HttpStatus.CONFLICT, "AUTH-003"),

  /* 3. USER – 사용자 */
  USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER-001"),
  USER_DUPLICATE_NICKNAME(HttpStatus.CONFLICT, "USER-002"),
  USER_NICKNAME_CHANGE_LIMITED(HttpStatus.FORBIDDEN, "USER-003"),
  USER_RE_REGISTRATION_FORBIDDEN(HttpStatus.FORBIDDEN, "USER-004"),
  USER_LOGIN_FAIL(HttpStatus.UNAUTHORIZED, "USER-005"),
  USER_SIGN_UP_FAIL(HttpStatus.UNAUTHORIZED, "USER-006"),

  /* 4. POST – 게시글 */
  POST_NOT_FOUND(HttpStatus.NOT_FOUND, "POST-001"),
  POST_INVALID_LINK(HttpStatus.BAD_REQUEST, "POST-002"),
  POST_CONTENT_TOO_LONG(HttpStatus.PAYLOAD_TOO_LARGE, "POST-003"),

  /* 5. COMMENT – 댓글 */
  COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "COMMENT-001"),
  COMMENT_PERMISSION_DENIED(HttpStatus.FORBIDDEN, "COMMENT-002"),
  COMMENT_CONTENT_REQUIRED(HttpStatus.BAD_REQUEST, "COMMENT-003"),

  /* 6. FOLLOW – 팔로우 */
  FOLLOW_TARGET_NOT_FOUND(HttpStatus.NOT_FOUND, "FOLLOW-001"),
  FOLLOW_ALREADY_FOLLOWING(HttpStatus.CONFLICT, "FOLLOW-002"),
  FOLLOW_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "FOLLOW-003"),

  /* 7. STAR – 즐겨찾기 */
  STAR_NOT_FOUND(HttpStatus.NOT_FOUND, "STAR-001"),
  STAR_ALREADY_STARRED(HttpStatus.CONFLICT, "STAR-002"),

  /* 8. RECOMMEND – 댓글 추천 */
  RECOMMEND_NOT_FOUND(HttpStatus.NOT_FOUND, "RECOMMEND-001"),
  RECOMMEND_ALREADY_RECOMMENDED(HttpStatus.CONFLICT, "RECOMMEND-002"),

  /* 9. TAG – 태그 및 검색 */
  TAG_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "TAG-001"),
  TAG_NOT_FOUND(HttpStatus.BAD_REQUEST, "TAG-002"),

  /* 10. SEARCH – 검색 */
  SEARCH_TERM_MISSING(HttpStatus.BAD_REQUEST, "SEARCH-001"),
  SEARCH_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "SEARCH-002"),

  /* 11. NOTIFICATION – 알림 */
  NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "NOTI-001"),
  NOTIFICATION_INVALID_STATE(HttpStatus.BAD_REQUEST, "NOTI-002"),

  /* 12. BADGE – 배지 */
  BADGE_ALREADY_UNLOCKED(HttpStatus.BAD_REQUEST, "BADGE-001"),
  BADGE_NOT_FOUND(HttpStatus.NOT_FOUND, "BADGE-002"),
  BADGE_UPDATE_CONFLICT(HttpStatus.CONFLICT, "BADGE-003"),

  /* 13. COMPANY – 기업 */
  COMPANY_NOT_FOUND(HttpStatus.NOT_FOUND, "COMP-001"),

  /* 14. AI – AI */
  CRAWLING_FAILED(HttpStatus.BAD_GATEWAY, "AI-001"),
  CONTENT_EXTRACTION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "AI-002"),
  SSL_ERROR(HttpStatus.BAD_GATEWAY, "AI-003"), // SSL 인증서 문제
  UNKNOWN_HOST(HttpStatus.BAD_GATEWAY, "AI-004"), // 호스트를 찾을 수 없음
  TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "AI-005"), // 네트워크 타임아웃
  HTTP_CLIENT_ERROR(HttpStatus.BAD_REQUEST, "AI-006"), // 4xx 에러
  HTTP_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "AI-007"), // 5xx 에러
  SELENIUM_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "AI-008"), // Selenium 동작 오류
  NETWORK_ERROR(HttpStatus.BAD_GATEWAY, "AI-009"), // 기타 네트워크 오류
  AI_REQUEST_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "AI-010"),

  /* 15. FILE */
  FILE_UPLOAD_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "FILE-001");

  private final HttpStatus httpStatus;
  private final String code;
}
